### PR TITLE
Stunner (jbpm designer NEXT) integration into kie-wb-common.

### PR DESCRIPTION
**Pull request by romartin**
This is the initial integration of the new jbpm designer, named Stunner, into kie-wb-common.
This code comes from this repo -> https://github.com/romartin/wirez
This PR depends on this one -> https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/289
@manstis Here is the small PR!! :P Lemme know something when possible. Good luck! :)
Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins fails due to the KIE BOM is not updated with this https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/289

**Comment by manstis** [comment]
@romartin I suspect you're going to need to use consistent branch names for Jenkins to be able to compile your PRs "together". ```droolsjbpm-build-bootstrap``` branch is called ```stunner``` and this one ```stunner-wb-integration```

**Comment by manstis** [comment]
@jlindop @tsurdilo @csadilek Want to help review? :-)

**Comment by romartin** [comment]
@manstis oh didnt know that making branches names match will make this PRs compile together... good point. Will rename the branch for the droolsjbpm PR right now htanks!

**Comment by romartin** [comment]
Hi guys, as @manstis commented, I have reopened the build-bootstrap PR with same branch name -> https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/290

**Comment by romartin** [comment]
how can I make this PR being rebuilt by Jenkins?

**Comment by manstis** [comment]
@romartin You need to ask nicely.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by romartin** [comment]
@manstis hahaha oh good! Thx :)

**Comment by romartin** [comment]
Oh love that green icon :)

**Comment by csadilek** [comment]
😵 

One thing I will ask is to run the code formatter e.g. to get rid of blocks like this with excessive new lines: https://github.com/romartin/kie-wb-common/blob/6ac02b7dd24c8a572d16effad6293288f32b9b8c/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/palette/impl/LienzoDefinitionSetPaletteImpl.java#L127

Doing that now (in the first commit) will make sure we have meaningful diffs in the future.

**Comment by romartin** [comment]
Hi @csadilek @manstis ,
Until geOffrey updates and fixes our code-style setting files (https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/tree/master/ide-configuration), I have tried to create manually the settings and added a new commit. Hopes this style is better now. I have done some cleans and rebased from master as well.
Thanks!

**Comment by romartin** [comment]
It's failing a test for the wb screens stuff, it does not happens locally, not sure if related, no updates on that modules done from my side

**Comment by romartin** [comment]
Jenkins please retest this.

**Comment by jlindop** [comment]
Looks good, and the tests and showcase are both working fine.
+1

**Comment by tsurdilo** [comment]
looks good to me too +1

**Pull request merged**
