### PR TITLE
GUVNOR-2346: added testcases

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
Please do not merge yet.

**Comment by csadilek** [comment]
Thanks, looks good to me but best for @manstis or @Rikkola to verify?

**Comment by manstis** [comment]
@jomarko, is this OK to review now?

**Comment by jomarko** [comment]
@manstis , yes, I think so

**Comment by Rikkola** [comment]
+1 from me. Creation of new projects can't be tested too well. This area will probably see some changes during the next 12 months and we don't want to break anything.

**Comment by csadilek** [comment]
Thanks.

master: 46c049e4a7a267afdd3662f120a0dcf52e5e3836

**Pull request closed without merging**
