### PR TITLE
JBPM-5387: Stunner integration into KIE and Drools Workbenches.

### PR DESCRIPTION
**Pull request by romartin**
Some minor things to achieve a better integration into KIE and Drools workbenches.
See https://issues.jboss.org/browse/JBPM-5387

### CODE REVIEW

**Comment by jlindop** [comment]
Tested together with https://github.com/droolsjbpm/kie-wb-distributions/pull/386  and looks good
+1

**Comment by romartin** [comment]
Hi @csadilek , thanks for the review! Good point on the callbacks, I have changed the behavior, the callbacl instance should never be null, that's really better, thanks! :)

**Comment by romartin** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
