### PR TITLE
Remove transitive  dependency to Stunner.

### PR DESCRIPTION
**Pull request by romartin**
Hey @manstis @pefernan @mbiarnes 
This commit fixes the wrong dependency from the workbench client module to stunner.
Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by romartin** [comment]
@manstis wondering why when I say "J please retest this", it always fails.. .and when you say that, it works...!? :)

**Comment by manstis** [comment]
@romartin Jenkins needs love and affection.

**Pull request merged**
