### PR TITLE
GUVNOR-2452: new exec server UI 

### PR DESCRIPTION
**Pull request by porcelli**
Updated version of PR #282

### CODE REVIEW

**Comment by porcelli** [comment]
@ederign enjoy ;)

**Comment by manstis** [comment]
I'll leave the review to Eder (thanks, great job) but shouldn't you squash these commits?

**Comment by manstis** [comment]
@porcelli you're all giving.. thanks for explaining the situation.

**Comment by ederign** [comment]
+1

**Comment by csadilek** [comment]
@porcelli @ederign thoughts?

**Comment by porcelli** [comment]
@csadilek i'd add logs.. and callsite are already covered. But I'm still in favor to not directly affect UI due a failed event, so I'd go for:
Callsite checks (done) + null checks in observer (if you meant if != null) + logging (on else of the null check)

**Comment by csadilek** [comment]
@porcelli ok that would be my preferred choice as well.

**Comment by csadilek** [comment]
All commits on 6.4.x:

2952f943295d6c4cd6133cde9af0e60fce0b4ddb
a282b7203d6c63985cb55f99dcce3fe30838c95c
126775c820e07df7c109d84a90b9a60de2fd7a6d
7cd038c0a9674e5ec0381ec4b681b962ff9dee26
b5b321d1a7691f289608ccf1be6740aa2b0c8b97
fb5a197c964939a07263fce8b5a87f8145ebca34
944abc7a365811ed705693281f6de5cbed0fccba

**Pull request closed without merging**
