### PR TITLE
UF-320: Adding counters for roles, groups and users on admin page

### PR DESCRIPTION
**Pull request by paulovmr**
* Added counters for roles, groups and users on admin page on kie-wb-webapp and kie-drools-wb-webapp.

adminpage2

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by manstis** [comment]
An interesting use of lamdas and anonymous inner classes :-) perhaps try to stay consistent either way ;-)

**Comment by paulovmr** [comment]
@manstis Good point :). I'll change it now.

@csadilek Thanks for the review. Please wait for my change before merging it. I'll change it on the [Uberfire PR](https://github.com/uberfire/uberfire/pull/541) as well.

**Comment by paulovmr** [comment]
Changed.

**Comment by csadilek** [comment]
Agreed, looks cleaner now ;).

**Pull request merged**
