### PR TITLE
Bug 1257819 - [GSS] (6.1.z) Rules are not populated in dropdown list in Test Scenarios in BRMS 6.1

### PR DESCRIPTION
**Pull request by Rikkola**
This PR is for 6.2.x
This and 3 others depend on each other:
https://github.com/droolsjbpm/kie-wb-common/pull/159
https://github.com/droolsjbpm/drools-wb/pull/95
https://github.com/droolsjbpm/jbpm-designer/pull/97
https://github.com/droolsjbpm/jbpm-form-modeler/pull/26

### CODE REVIEW

**Comment by psiroky** [comment]
Build failure not related to changes in this PR. Fix is prepared https://github.com/droolsjbpm/droolsjbpm-integration/pull/239

**Comment by manstis** [comment]
+1 to merge.

**Comment by psiroky** [comment]
The test fail is still there, even with changes from https://github.com/droolsjbpm/droolsjbpm-integration/pull/239. I have no idea if it is related to the changes here though. I originally thought the first build failed for different reason, sorry for the confusion.

**Comment by csadilek** [comment]
6.2.x: 7e6c0b7fbb9fc14a99d2d82509325ad6624b943b

**Pull request closed without merging**
