### PR TITLE
[6.4.x] GUVNOR-2365: Repository remains in repositories list after it is deleted

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
A test (no matter how trivial) would be nice.

**Comment by paulovmr** [comment]
@manstis Ok, you are right, I will make one. Thanks!

**Comment by paulovmr** [comment]
@manstis The tests and comment have been made.

**Comment by manstis** [comment]
+1 to merge. Thanks!

**Comment by psiroky** [comment]
Merged into 6.4.x.

**Pull request closed without merging**
