### PR TITLE
Fix the build after data source management merge.

### PR DESCRIPTION
**Pull request by mbarkley**

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
This fixes the failing optaplanner-wb and drools-wb builds.

**Comment by manstis** [comment]
It might be worth checking kie-wb deployed to Wildfly or something to check we don't need to filter in assemblies.

**Comment by csadilek** [comment]
@manstis we are verify that before merging.

**Comment by csadilek** [comment]
Verified that deployment is fine. Merging, deploying snapshots and triggering builds.

**Pull request merged**
