### PR TITLE
BZ1275325: WAS: indexing fails with ContextNotActiveException

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1275325

Implementation of EJB was flawed; it was neither an "no interface" bean, nor a "local interface" bean.

### CODE REVIEW

**Comment by mswiderski** [comment]
@manstis just a question as I ran into it locally when trying your early bits - when I opened project explorer I got a popup window with NoSuchMethodError referring to SimpleAsyncExecutorService. Though it might have been only my local issue though I wanted to double check that is not a general one.

**Comment by manstis** [comment]
@mswiderski I've ran kie-drools-wb on EAP, Wildfly and EAP with these changes and on all occasion navigated to Authoring->Project Explorer->an asset->opened the asset.. Each installation was fresh - but we don't persist any information relating to SimpleAsyncExecutorService, so I wouldn't have expected problems. Let me just try kie-wb on EAP with these changes, in case I've missed something somewhere that was not caught as a compilation error.

**Comment by manstis** [comment]
@mswiderski Hi, I ran kie-wb on EAP and generally fiddled around on Project Explorer. No errors thrown.  Project Explorer uses the [SimpleAsyncExecutorService](https://github.com/droolsjbpm/kie-wb-common/blob/master/kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/main/java/org/kie/workbench/common/screens/explorer/backend/server/ExplorerServiceImpl.java#L231) to persist it's state; however it's usage hasn't been modified by any of these PRs.

**Comment by mswiderski** [comment]
@manstis then I +1 this :) great job!

**Comment by csadilek** [comment]
6.3.x: 0bbad9a1d9e84e6bc32d5a742e1dce16f060b196

**Pull request closed without merging**
