### PR TITLE
JBPM-5043: general properties panel title not updated when a field is selected

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis hello Mike, would you mind reivew this PR?
Thanks.

**Comment by manstis** [comment]
The tests repeat a lot of common setup code. Might be worth moving them into a new test class with applicable Before code? Otherwise seems fine to me.

**Comment by wmedvede** [comment]
@manstis See the changes. Enough from my side.

**Comment by manstis** [comment]
+1 to merge (when Jenkins is green)

**Comment by csadilek** [comment]
6.4.x: 7dcf5e40c38713a8d623c025afa2379f2df42250

**Pull request closed without merging**
