### PR TITLE
Stunner - imports arranged by KIE Group convention

### PR DESCRIPTION
**Pull request by hasys**
- getting rid of unused imports
- getting rid of star notation
- import reorder according to KIE Group convention

KIE Group Rules:
No reason to add unused import, star notation is not allowed except static imports for org.junit.Assert, org.assertj.core.api.Assertions, org.mockito.Mockito.

Alphabetically sorted groups of imports:
> **import** *java*;
> **import** *javax*;
> 
> **import** *everything.else*;
> 
> **import static** *everything*;

How to organize imports for future PR: use automatic import sorting tool in your IDE.

### CODE REVIEW

**Comment by psiroky** [comment]
+1 to merge and enforce this!

**Comment by hasys** [comment]
Hi @romartin,
there are imports reordering as we talked before.

For new code import organizing just update your IDEA configuration and use Ctrl+Alt+O for single file or left mouse button on project name in Project Explorer -> Optimize Imports), also you can set *Optimize import on the fly* option (Settings -> Editor -> General -> Auto Import -> Optimize import on the fly) and don't care any more how they are organized :).

Keep in your mind, that https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/342 fix one import setting for IDEA and also force build fail on compile in case of imports are not organized properly.

P.S. compilation error is not related to build, but to https://github.com/errai/errai/pull/217

**Comment by psiroky** [comment]
jenkins retest this

**Comment by manstis** [comment]
@hasys Hi. I propose closing this PR as I'll submit a "code formatting" (which includes imports arrangement) after https://github.com/droolsjbpm/kie-wb-common/pull/605 is merged.

**Comment by hasys** [comment]
Hi @manstis, yes, I guess we can close it for now. @psiroky, sorry for the delay, after https://github.com/droolsjbpm/kie-wb-common/pull/605 will be merged we will format not only import but all styling violations at once.

**Pull request closed without merging**
