### PR TITLE
JBPM-4833 - Data Modeller MVP, Tests, and related improvments

### PR DESCRIPTION
**Pull request by wmedvede**
-DataObjectBrowser, MPV improvements + tests + i18n review

(cherry picked from commit 78a8e665131c3fc31a360ac3085561bba1832560)

### CODE REVIEW

**Comment by wmedvede** [comment]
This is the peer PR for the already merged into 6.4.x branch https://github.com/droolsjbpm/kie-wb-common/pull/233

Ready to merge.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
master: fe98abdcecebb709f0eb76fd887fa1556f097328

**Comment by csadilek** [comment]
I am reverting this on 6.4.x as it breaks the build there (master is fine). Adding a default constructor to DataObjectBrowser fixed the issue for me but I am not sure it's worth taking the risk of putting this into 6.4.x as it's mainly a refactoring. /cc @wmedvede

**Comment by csadilek** [comment]
revert: 272bb197d428280a892842fe3e952def0a799043

**Pull request closed without merging**
