### PR TITLE
GUVNOR-2909 : Library: Add branch selector on the header (along with the repository selector).

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2909

@paulovmr Hi, take a look please.

### CODE REVIEW

**Comment by paulovmr** [comment]
@Rikkola Hi, the changes look good, just to minor comments:

* Some files weren't formatted, other were. I think would be good to format all modified files.
* Is there a reason why you changed some interface methods to `final`?

**Comment by Rikkola** [comment]
@paulovmr Updating formats, rebasing with latest. 
And about final, I just have an obsession with final, not really needed for interfaces.

**Comment by Rikkola** [comment]
@jomarko That works since the branch in repository is null by default and then the branch in event is again null. I'll set some value to `repository.getDefaultBranch()` just in case.

**Comment by jomarko** [comment]
@Rikkola thanks for explanation.

**Pull request merged**
