### PR TITLE
Use custom FormRenderingContext in stunner properties forms that cont…

### PR DESCRIPTION
**Pull request by mbarkley**
…ains path of resource.

### CODE REVIEW

**Comment by mbarkley** [comment]
@pefernan @romartin This change introduces a custom `FormRenderingContext` to Stunner properties forms containing the `Path` of the diagram for the given properties form.

Could one of you please review this?

**Comment by pefernan** [comment]
@mbarkley looks fine, I tried it on the stunner showcase and works fine. How can I test it properly?

**Comment by mbarkley** [comment]
I just pushed an update adding a unit test.

@pefernan The unit test now covers the only change in functionality. Everything else should behave the same.

**Comment by mbarkley** [comment]
Jenkins, retest this.

**Comment by manstis** [comment]
@pefernan Please let me know when you're OK for this to be merged.

**Comment by pefernan** [comment]
+1

**Pull request merged**
