### PR TITLE
[6.5.x] RHBPMS-4373: Singleton runtime strategy is always shown in container configuration

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/RHBPMS-4373

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please restest this.

**Comment by karreiro** [comment]
Jenkins please restest this.

**Comment by karreiro** [comment]
Jenkins please restest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
ok all merged/deployed now, so one more time. please jenkins retest this.

**Comment by csadilek** [comment]
@karreiro we finally have a working build here. Your PR doesn't compile as ClientRuntimeStrategy.PER_CASE doesn't exist on 6.5.x. Can you please take a look?

**Comment by karreiro** [comment]
Thanks you, @csadilek :-)

**Comment by csadilek** [comment]
+1

**Pull request merged**
