### PR TITLE
[6.5.x] RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset (#437)

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHBRMS-349

    (cherry picked from commit 903d0068908a59bb09ced6da9d2aa0a1165656cc)

This is the corollary of https://github.com/droolsjbpm/kie-wb-common/pull/437 for 6.5.x.

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:-

- https://github.com/uberfire/uberfire/pull/488
- https://github.com/droolsjbpm/kie-wb-common/pull/449

**Comment by manstis** [comment]
Jenkins please retest this (now the upstream issue is fixed)..

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola Hi, would you mind reviewing this please (it's a cherry-pick). Thanks.

**Comment by Rikkola** [comment]
Nice, I see you removed some dead code.
+1

**Pull request merged**
