### PR TITLE
GUVNOR-2703: adding user's feedback on exec server operations.

### PR DESCRIPTION
**Pull request by porcelli**
Depends on #477

### CODE REVIEW

**Comment by porcelli** [comment]
@mswiderski please review ;)

**Comment by mswiderski** [comment]
tested locally and I see fly over in case there is an error on kie server so it looks good to me.

One thing (not directly related) the notification popup on container card does not work for me... though I couldn't figure out what might caused it.

so +1 for this change

**Comment by porcelli** [comment]
jenkins please retest this

**Comment by porcelli** [comment]
jenkins please retest this

**Pull request merged**
