### PR TITLE
GUVNOR-2464: Move StyleHelper from kie-wb-common to uberfire-extensions

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2464

### CODE REVIEW

**Comment by manstis** [comment]
Also see https://github.com/uberfire/uberfire-extensions/pull/238

**Comment by manstis** [comment]
@porcelli ...

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 21676f4477d1f144adc2b30c31f6dbe7825552d8

**Pull request closed without merging**
