### PR TITLE
BZ1193484: Roles added to Projects are ignored by Business Central

### PR DESCRIPTION
**Pull request by manstis**
See https://github.com/droolsjbpm/kie-wb-common/pull/142

- This commit adds filtering for Social Events

(cherry picked from commit 0b2ae8f1f831186a404e0a87bcc0bfd03f96d307)

### CODE REVIEW

**Comment by manstis** [comment]
** DO NOT MERGE UNTIL I GET AGREEMENT FOR THIS TO BE IN 6.3.x **

**Comment by manstis** [comment]
*** AGREEMENT TO MERGE INTO 6.3.x STILL PENDING ***

**Comment by etirelli** [comment]
The merge was approved during the PM call. +1 to merge.

**Comment by csadilek** [comment]
Thanks.

6.3.x: 0b49bd33377565a926448b45695bd35e530c0f58

**Pull request closed without merging**
