### PR TITLE
UF-251: Timeline perspective - latest changes - links to People persp…

### PR DESCRIPTION
**Pull request by paulovmr**
…ective broken

### CODE REVIEW

**Comment by manstis** [comment]
I know it's a small change; but since the change is in a Presenter; we'd really be looking for some (basic) Unit Test to accompany the change (and I'm sure the test will take longer to write than the change!) ;)

**Comment by paulovmr** [comment]
@manstis Ok, I agree with you, will do the test :) Thanks!

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 453240d0f7fa1e935df27a2bc82e847e41face2c

**Pull request closed without merging**
