### PR TITLE
latest Zanata translation changes in kie-wb-common from 2016-07-07

### PR DESCRIPTION
**Pull request by kiereleaseuser**

### CODE REVIEW

**Comment by manstis** [comment]
Return of the slash..... (luckily it's a non-issue now).

+1 to merge.

**Comment by manstis** [comment]
(Waiting on Jenkins before merging)

**Comment by mbiarnes** [comment]
@manstis are these slashes not anymore "dangerous" for the line endings?

**Comment by manstis** [comment]
@mbiarnes AFAIK errai was changed to handle the slashes..

**Pull request merged**
