### PR TITLE
Fix kie-wb-common-examples-screen-client ~> beans.xml

### PR DESCRIPTION
**Pull request by karreiro**
Updates kie-wb-common-screens/kie-wb-common-examples-screen/kie-wb-common-examples-screen-client/src/main/resources/META-INF/beans.xml file.

### CODE REVIEW

**Comment by manstis** [comment]
@karreiro Hi, what's this PR "fixing"? Examples screen runs fine for me... when you submit PRs please try to give more description as to what the issue is and how the fix resolves it (linking to a JIRA is a good idea too). Thanks, Mike

**Comment by karreiro** [comment]
Hi @manstis. I've noticed that the others beans.xml usually exclude client side classes to avoid to deploy them. I caught this problem when I was trying to run kie-wb-common and kie-wb-distributions together on Intellij. I didn't open an issue because it does not look like a bug, it is just a little adjust. :)

**Comment by manstis** [comment]
@karreiro Thanks for the explanation.

+1 to merge.

**Comment by manstis** [comment]
ok to test.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
