### PR TITLE
BZ1268311: Server Management Browser: Container info display two remove buttons

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1268311

### CODE REVIEW

**Comment by porcelli** [comment]
OMG, took me a while to build all platform, update my docker to work on recent OSX version.. to finally get a kie-server to test.... 
But after all this is not an issue on server management UX, it's a UF issue, as it now has all types of panels behaving like a multi panel. I will close (not merge) and file a new UF jira for it.

**Comment by manstis** [comment]
OK, you know what UF should and should not do these days. To be honest I originally thought this was a UF issue but then I saw the ```ContainerInfoPresenter``` was adding a close button to the menu whereas this seemed to be provided by UF.

**Comment by porcelli** [comment]
You're right... UF should provide such thing... but this would be an enhancement... so for now we can leave this PR open, but first let's address UF bug first.

**Comment by manstis** [comment]
hehe, now I'm confused.

As far as I can tell, UF *does* provide the close button (the ```...``` then ```x``` icons... remember Christian wants to change this back to having ```x``` on the main menu bar).. This is why the BZ had been raised: UF provides a close icon and so did the screen.

**Comment by porcelli** [comment]
hehe... I know that sounds confusing.

Original SimpleWorkbenchPanelPresenter doesn't have support for close, what is expected, but it would be good to have a ClosableSimpleWorkbenchPanelPresenter.

The UF issue that I'll report basically mentions that none of existing PanelPresenter's are behaving as expected.

**Comment by porcelli** [comment]
UF issues:
https://issues.jboss.org/browse/UF-235
https://issues.jboss.org/browse/UF-236

**Comment by manstis** [comment]
@porcelli The two referenced JIRAs are marked as resolved; is this PR "good to go" now?

Feel free to re-assign if you're still plunged in to the world of micro services for the foreseeable future.

**Comment by manstis** [comment]
@cristianonicolai Hi, I've reassigned to you as @porcelli seems a bit busy elsewhere.

Alexandre wanted two UF issues resolved prior to merging this, so I assume this can now be reviewed.

**Comment by cristianonicolai** [comment]
@manstis sure, I can review it.

**Comment by cristianonicolai** [comment]
@manstis @porcelli , ok so now we have no close button :). Is that the intended behaviour or should we also update the ServerManagementPerspective to use the new ClosableSimpleWorkbenchPanelPresenter?

**Comment by cristianonicolai** [comment]
just to be clear, no close buttons on master. For 6.3.x branch this should be fine ( one close button ).

**Comment by manstis** [comment]
New PR for 6.3.x raised.

See https://github.com/droolsjbpm/kie-wb-common/pull/122

Closing this PR.

**Comment by cristianonicolai** [comment]
@manstis I couldn't explain it better, thanks! :) Same situation happens for jbpm-console-ng, we got several listing screens, ex process instance list, task list, that should not be closable, but when you select an item in the list, we open the details in the same perspective. So the list should not be closable but the details screen should. 

@porcelli would that be the case that instead of doing placemanager.goTo("id"), we should instead use placemanager.goTo( final String identifier, final PanelDefinition panel ) using a new panel definition that uses the ClosableSimpleWorkbenchPanelPresenter as presenter?

**Pull request closed without merging**
