### PR TITLE
JBPM-5402 - Stunner - rename General Settings to General - and moving…

### PR DESCRIPTION
**Pull request by tsurdilo**
… fielddef label to constants

### CODE REVIEW

**Comment by jlindop** [comment]
Tested and looks good. Thanks for fixing the typos in constants earlier.
+1

**Comment by manstis** [comment]
Out of interest how is ```@FieldDef``` i18n'ed? I assume the "label" is used in the UI; however we cannot substitute the constants for GWT ResourceBundles and our regular i18n mechanism as (again) I assume Form Modeller needs the annotations at code-generation (compile) time and not runtime. @pefernan Can you advise?

**Comment by pefernan** [comment]
@manstis at this point they aren't i18n'ed. This is the first version of the dynamic engine and it's going to be refactored as soon as I have the M1 done. If you want we can have a chat about that, I'll be happy to expalin in detail how it works and I can get some advice from you for the new version ;)

**Comment by manstis** [comment]
@pefernan Hi, I was just curious; now I know at the moment they are not i18n'ed. 

I guess in the future ```@FieldDef``` may either replace ```label``` with ```label-key``` and a lookup performed at runtime; or to preserve backwards compatibility a ```label-key``` property added to the annotation in addition to ```label```. 

Assuming you use Errai UI this could be achieved with generated ```TranslationKey``` implementations based on ```label-key``` and ```TranslationService``` (or if you're using GWT then similarly generated classes).

**Comment by pefernan** [comment]
@manstis yeah the idea is to use the TranslationService for this if possible. 
At the begining this feature was intended as an "experiment" and now it's being used intensively, as I said it will require a big refactor.

**Pull request merged**
