### PR TITLE
RHBPMS-4430: Remove Russian and Chinese (Traditional) from language dropdown

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:

* https://github.com/droolsjbpm/kie-wb-common/pull/532
* https://github.com/droolsjbpm/kie-wb-distributions/pull/387

**Comment by paulovmr** [comment]
@krisv The issue [RHBPMS-4430](https://issues.jboss.org/browse/RHBPMS-4430) hasn't all the ACKs yet. Should we go ahead and review/merge it anyway?

**Comment by manstis** [comment]
@paulovmr IDK if there may be changes needed elsewhere relating to [DatePicker](https://github.com/uberfire/uberfire/blob/master/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/DatePicker.java). Could you please check with @nmirasch as she has made changes in that area in the past relating to Locales.

**Comment by paulovmr** [comment]
Hi @nmirasch , we are removing the languages Russian and Chinese (Traditional) from the workbench. Is there something relating to [DatePicker](https://github.com/uberfire/uberfire/blob/master/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/DatePicker.java) to remove or change too or we don't have to worry about that?

**Comment by paulovmr** [comment]
@etirelli The issue [RHBPMS-4430](https://issues.jboss.org/browse/RHBPMS-4430) hasn't all the ACKs yet. Should we go ahead and review/merge it anyway?

**Comment by etirelli** [comment]
@paulovmr yes, please merge.

**Pull request merged**
