### PR TITLE
BZ1277556: Project selector Dropdown becomes useless with the right(wong) OU/Repository/Project name lengths

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1277556

This only affects 6.3.x (more by luck). The "Project" ```CustomDropdown``` is aligned along the right-hand edge (compared to OU and Repository dropdowns, that are aligned left). This can lead to the scenario described in the BZ. This fix simpy re-positions the drop-down if clipped.

See https://issues.jboss.org/browse/UF-246 too (as it's related).

### CODE REVIEW

**Comment by manstis** [comment]
@cristianonicolai Hi, since you've become the resident UI-whizz-kid do you mind taking a look at this?

**Comment by manstis** [comment]
@Rikkola Hi... I'd hoped @cristianonicolai may have reviewed this in time for todays deadline.. would you mind taking a look please, so it can be merged today? Thansks.

**Comment by manstis** [comment]
ok to test

**Comment by Rikkola** [comment]
+1
This is a rendering issue so hard to unit test. There would have to be a Selenium test for this.

**Comment by manstis** [comment]
The CI failure relates to https://github.com/droolsjbpm/jbpm/commit/509b56fa47f6013cd771295797180a2d963f3269

**Comment by mswiderski** [comment]
merged into 6.3.x with https://github.com/droolsjbpm/kie-wb-common/commit/98b2c47ba3525fb75e5d6a05a5d20121f80e9dbf

**Comment by cristianonicolai** [comment]
@manstis really sorry, I somehow missed it. :(

**Pull request closed without merging**
