### PR TITLE
JBPM-4833 - Data Modeller MVP, Tests, and related improvments

### PR DESCRIPTION
**Pull request by wmedvede**
- NewFieldPopup, MPV improvements + tests + i18n review

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis 
Hello Mike, would you mind review this PR.
Thanks!

**Comment by wmedvede** [comment]
don't know what could fail with jenkins, but it works well

**Comment by psiroky** [comment]
@wmedvede if you click on the red cross left of the commitId (or click on the "Details" link), you will get to the build and can browse the logs to see why the build failed.

jbpm-4833 - data modeller mvp tests and related improvments by wmedvede pull request -185 droolsjbpm-kie-wb-common - google chrome_002

**Comment by psiroky** [comment]
The failure is not related to changes in this PR. The build failed when building droolsjbpm-integration repository. I re-triggered the job to see if we can reproduce it again.

**Comment by wmedvede** [comment]
@psiroky  great, thanks.

**Comment by csadilek** [comment]
+1, but waiting for @manstis to confirm.

**Comment by manstis** [comment]
+1 to merge (probably have merge conflicts on the license headers that are now out dated following Michael B's recent PR)

**Comment by csadilek** [comment]
Thanks.

master: 825e1cb1377ba298dd997c9d67ad953cd425d96d

**Pull request closed without merging**
