### PR TITLE
Bug 1304447 - [GSS](6.2.z) Not able to select specific branch from repository

### PR DESCRIPTION
**Pull request by Rikkola**
Changed the information about current branch to client side.

https://github.com/droolsjbpm/guvnor/pull/264
https://github.com/droolsjbpm/kie-wb-common/pull/278
https://github.com/droolsjbpm/drools-wb/pull/132
https://github.com/droolsjbpm/jbpm-console-ng/pull/341
https://github.com/droolsjbpm/jbpm-designer/pull/161
https://github.com/droolsjbpm/jbpm-form-modeler/pull/38
https://github.com/droolsjbpm/optaplanner-wb/pull/38
https://github.com/droolsjbpm/kie-wb-distributions/pull/209

### CODE REVIEW

**Comment by manstis** [comment]
Riddle me this, riddle me that... IIRC ```ProjectContextChangeEvent``` is used by Project Explorer to signal changes of erm, context. This is ```Portable``` meaning Errai will happily send it to the server (and hence to all "federated" attached clients).. how do you prevent change in branch selection affecting all Users?

**Comment by Rikkola** [comment]
Not a big fan of your riddle ;)
Checking if it can be made not portable. Context should be client side and per user.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
master: b92471a785557a204cd09fdad17b0172e5a32d32

**Pull request closed without merging**
