### PR TITLE
[6.5.x] GUVNOR-2679 : [GSS](6.3.z) Custom changes to pom.xml are being overwritten (#463)

### PR DESCRIPTION
**Pull request by Rikkola**
RHBPMS-4190 : [GSS](6.3.z) Custom changes to pom.xml are being overwritten
(cherry picked from commit 7229b74cf64702f2ab3ed0bb706be8eae9e13467)

https://issues.jboss.org/browse/RHBPMS-4190
https://issues.jboss.org/browse/GUVNOR-2679

Had to do some adjustments, mainly to make the tests fit 6.5.x branch.

### CODE REVIEW

**Comment by Rikkola** [comment]
@karreiro @manstis Please review when you have time.

**Comment by Rikkola** [comment]
Hmm, this might be missing few files. Rechecking.

**Comment by Rikkola** [comment]
Ok. All in.

**Comment by manstis** [comment]
@Rikkola you have a failing test - but it is fixed by https://github.com/droolsjbpm/kie-wb-common/pull/476/commits/c52590c3a4ba06dc35890623fb58a251706063f5 (in one of my pending 6.5.x PRs).

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
