### PR TITLE
JBPM-5033: DM: type selection dropdown in 'New Field' modal too short

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis Hello Mike, would you mind review this PR?
Thanks.

**Comment by wmedvede** [comment]
Just for record,
the build error reported by the job is:

15:10:43 /home/jenkins/workspace/kie-wb-common-pullrequests-6.x/upstream-repos/droolsjbpm-integration/kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/KieSessionClientCommandObject.java:[65,7] error: KieSessionClientCommandObject is not abstract and does not override abstract method delete(FactHandle,State) in 

I've chatted with @mswiderski and he pushed some missing commits, so it's expected that the build will be fixed.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
6.4.x: d97b8f06a1f2c4ec1fe923411fe67d7b2a899931

**Pull request closed without merging**
