### PR TITLE
RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHBRMS-349

This PR ensures the ```MenuItems``` enabled/disabled state is initialised correctly when the Menu's items are requested (by, for example, navigating to the Authoring Perspective).

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/uberfire/uberfire/pull/483
- https://github.com/droolsjbpm/kie-wb-common/pull/437
-

**Comment by manstis** [comment]
@ederign @cristianonicolai @paulovmr Mind taking a look?

**Comment by ederign** [comment]
+1.

**Comment by manstis** [comment]
Thanks @ederign

**Pull request merged**
