### PR TITLE
GUVNOR-2452: new exec server UI

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by psiroky** [comment]
The build failed because of branch name mismatch. This PR uses `porcelli-finished-exec-server-ui-final` and the https://github.com/droolsjbpm/droolsjbpm-integration/pull/344 uses `porcelli-finished-exec-server-ui`.

The tooling is just not smart enough to figure this one out...

**Comment by ederign** [comment]
@porcelli  https://www.dropbox.com/s/2eqo35z0rgrqbeg/282.patch?dl=0
Made some comments: search for "porcelli"

**Comment by porcelli** [comment]
@ederign review updated

**Comment by porcelli** [comment]
I'll open another PR with same branch name

**Pull request closed without merging**
