### PR TITLE
Code Formatting: Part 1

### PR DESCRIPTION
**Pull request by manstis**
Following merge of https://github.com/droolsjbpm/kie-wb-common/pull/605 this PR contains CODE FORMATTING CHANGES only. Since it's proving to be a large task this PR contains code formatting for the following modules:-

- kie-wb-common-stunner-backend
- kie-wb-common-stunner-client
- kie-wb-common-stunner-core

Code formatting includes:-

- Running of our standard code formatter over code
- Manual review adding missing ```final``` modifiers (it's use was inconsistent)
- Manual review splitting method signatures across multiple lines (it's use was inconsistent)
- Removal of white-space (e.g. empty lines before closing braces etc)

Modules outstanding:-

- kie-wb-common-stunner-extensions
- kie-wb-common-stunner-sets
- kie-wb-common-stunner-showcase

### CODE REVIEW

**Comment by manstis** [comment]
@hasys @romartin @csadilek Want to look before merge?

**Comment by hasys** [comment]
Hi @manstis, thank you for your PR!
but in IDEA configuration of KIE Group style was a small bug, we fixed it now, but I guess we need to rerun formatter over the code again. Fixed configuration you can found here: https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/ide-configuration/intellij-configuration/code-style/intellij-code-style_droolsjbpm-java-conventions.xml Sorry for the inconvenienceю

**Comment by manstis** [comment]
@romartin @hasys Reformatted with the latest IDEA code-style following https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/356

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by hasys** [comment]
Sorry for late response, but we had to wait until https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/358 will be resolved.

**Pull request merged**
