### PR TITLE
BZ#1316151: error shown only once

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by wmedvede** [comment]
@jomarko Hello Jozef, thanks for the fix. I'm in the midle of a JIRA that touches the same class. So I prefer to not merge this PR yet prior evaluation if the other fix is "affected by" or "can affect" this new PR. I'll keep you posted as soon I can.

Regards,
Walter.

**Comment by jomarko** [comment]
No problem @wmedvede , take so much time as you need.

**Comment by Rikkola** [comment]
A test for the fix would prevent it from breaking again in the future.

**Comment by csadilek** [comment]
Yes, this is a presenter fix and as such definitely requires a test to be merged.

**Comment by jomarko** [comment]
@Rikkola @csadilek , I understand, I will let you know, when I will be complete with tests for this PR

**Comment by wmedvede** [comment]
@jomarko Hello Jozef, this is PR we already chatted and emailed about. So I'll close it.
Thanks again for your help with this.

Regards,
Walter.

**Comment by wmedvede** [comment]
@csadilek Hi Christian, could you please close this PR since there was some overlapping and the issue is already solved.

Thanks.

**Comment by jomarko** [comment]
@wmedvede no problem. Maybe I will help you next time.

**Pull request closed without merging**
