### PR TITLE
JBPM-5371: Stunner - move BPMN custom property editors from forms mod…

### PR DESCRIPTION
**Pull request by jlindop**
…ules into bpmn modules

### CODE REVIEW

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
bpmn specific code should ultimately not be in kie-wb-common, but in a jbpm repo. Is it plannend to move this later? @romartin @jlindop

**Comment by jlindop** [comment]
@csadilek Yes, I believe we're planning to move the bpmn code to a different repo. When @romartin migrated the stunner code to kie-wb-common, he mentioned that he'd prefer to keep the bpmn code here for now.

**Comment by csadilek** [comment]
@jlindop ok thanks.

**Pull request merged**
