### PR TITLE
PLANNER-618 Workbench: Use org.jboss.errai.ioc.client.api.ManagedInstance instead of BeanManager where possible

### PR DESCRIPTION
**Pull request by mcimbora**
Removes unused methods from `DomainHandler` class hierarchy.

### CODE REVIEW

**Comment by csadilek** [comment]
+1 (I'd change the commit message though to ```Remove unused methods from DomainHandler``` or add that to the existing one).

**Comment by wmedvede** [comment]
@mcimbora @csadilek 
Hello guys,

I saw that in previous PRs you made some changes that affects things like JPADomain, DroolsDomain, etc. All this XXXDomain things are related to the content of the data modeler tool windows, etc.

So the question that came up to my mind is, are you @mcimbora testing/verifing that all the tool windows continues working properly with the changes, i.e., checking that drools parameters configuration works properly, persitable data objects, etc. (with for example two editors opened at the same time), or are you only testing the planner related stuff?

Regards,
Walter.

**Comment by mcimbora** [comment]
@wmedvede, I have to admit the testing is mainly planner-related. I am aware this possibly affects multiple modules, however the change was based on an assumption that the methods have no usage. Are you aware of any code which utilizes the removed methods?

**Comment by wmedvede** [comment]
Hello @mcimbora , 
I haven't checked exactly if only a couple of un-used methods were removed or the changes also include some other modification. But I believe this is the typical case that requires a verification to be sure all tool windows continues working. It shouldn't take too much time. So I'll appreciate if you please can take a look and be sure it is so.

Thanks!!

**Comment by mcimbora** [comment]
@wmedvede I'll go through it, thanks for the insight :-)

**Comment by mcimbora** [comment]
@wmedvede I went through the affected screens and everything seems to work fine. Additionally I was able to set drools-wb in multi module IDEA setup (drools-wb + kie-wb-common + guvnor) - created https://github.com/droolsjbpm/drools-wb/pull/244

**Comment by mcimbora** [comment]
@csadilek Commit message fixed.

**Comment by csadilek** [comment]
Thanks for the heads-up @wmedvede and for verifying @mcimbora. My +1 is based on the fact that the methods aren't used / have no call sites.

**Pull request merged**
