### PR TITLE
JBPM-4625 Generation of JPA enabled models

### PR DESCRIPTION
**Pull request by wmedvede**
- UberfireDocks integration

### CODE REVIEW

**Comment by manstis** [comment]
@ederign Could you please review, since Walter has integrated your Docks.

**Comment by wmedvede** [comment]
Mike, with reference to the Docks it self, there's not to much to see in kie-wb-common since the Docks are just a screen.
That's the way the docs are created, and the should be basically created at each web app.

    private void setupDocks() {
        uberfireDocks.register(
                new UberfireDock( UberfireDockPosition.EAST, new DefaultPlaceRequest( "DroolsDomainScreen" ), "AuthoringPerspective" ).withSize( 450 ),
                new UberfireDock( UberfireDockPosition.EAST, new DefaultPlaceRequest( "JPADomainScreen" ), "AuthoringPerspective" ).withSize( 450 ),
                new UberfireDock( UberfireDockPosition.EAST, new DefaultPlaceRequest( "AdvancedDomainScreen" ), "AuthoringPerspective" ).withSize( 450 )
        );
    }

**Comment by ederign** [comment]
@manstis agree with Walter. Do still need a review? 

I'm like John Snow in this source code :)

**Comment by manstis** [comment]
Taken.. I'll look at tomorrow - it was worth a try assigning to somebody else ;)

**Comment by wmedvede** [comment]
the second commit is just some i18n

**Pull request merged**
