### PR TITLE
BZ1268309: Register Server form display red text in label after incorrect connect

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1268309

### CODE REVIEW

**Comment by manstis** [comment]
Unfortunately it's not simple to add a test for ```KeyPressEvents```.. but if you want me to investigate further I will.

**Comment by porcelli** [comment]
Try check this package content for keypress https://github.com/porcelli-forks/kie-wb-common/tree/master/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/test/java/org/kie/workbench/common/screens/server/management/client/util

**Comment by porcelli** [comment]
https://github.com/droolsjbpm/kie-wb-common/commit/8d1c6533f2acb93e39047a9787dd0f1d15a3af6b

**Comment by porcelli** [comment]
@manstis tests done ;)

**Comment by manstis** [comment]
*kie-wb-common*
(6.3.x) http://github.com/droolsjbpm/kie-wb-common/commit/97b41b4a3

**Pull request closed without merging**
