### PR TITLE
GUVNOR-2886 : Meta data: Make External Link clickable

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2886

### CODE REVIEW

**Comment by Rikkola** [comment]
@manstis, @karreiro, anyone. I could use a review please.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola said he'd add support for re-entering "link" mode when the "edit" mode ```Textbox``` looses focus.

**Comment by Rikkola** [comment]
@manstis Ok, on blur done.

**Pull request merged**
