### PR TITLE
[6.3.x] GUVNOR-2459: NPE when open an Organization Unit that doesn't have a repository yet

### PR DESCRIPTION
**Pull request by manstis**
*** DO NOT MERGE ***

*** @Rikkola Can you please check if we should be committing to 6.3.x? ***

==========================================================================

See https://issues.jboss.org/browse/GUVNOR-2459

This is the corollary of https://github.com/droolsjbpm/kie-wb-common/pull/315 for 6.3.x

(cherry picked from commit a08a9e5a9c9299cb02bf0102138c31d0b944b31e)

Conflicts:
	kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/ProjectExplorerContentResolverTest.java

### CODE REVIEW

**Comment by Rikkola** [comment]
No we should not at this point. 
Only tickets that get approved to the next patch release and after the previous patch is done. So right now we are on hold.

**Comment by Rikkola** [comment]
I have a list of commits that need to go in once we have green light and this is on that list. If this PR  does not bother anyone we can leave it open for now.

**Comment by Rikkola** [comment]
This should go in now or never. Asking for permissions.

**Comment by Rikkola** [comment]
Made new PR that replaces this with a correct commit message. 
https://github.com/droolsjbpm/kie-wb-common/pull/347

This one can now be rejected.

**Comment by manstis** [comment]
Rejected, replaced by https://github.com/droolsjbpm/kie-wb-common/pull/347

**Comment by Rikkola** [comment]
Thank you @manstis

**Pull request closed without merging**
