### PR TITLE
[6.5.x] RHBRMS-2564 : Org.unit/repo/project navigation missing in standalone authoring perspective (#473)

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/RHBRMS-2564

(cherry picked from commit b46beb60ff0fe2b9e3458dfab2b117a2aa2e2db1)

Almost the same as the one for master. Got a conflict in BaseViewPresenterUpdateTest and had to make some adjustments for it to fit the 6.5.x.

### CODE REVIEW

**Comment by Rikkola** [comment]
@karreiro @manstis If you could please review.

**Comment by manstis** [comment]
@Rikkola you have a failing test - but it is fixed by https://github.com/droolsjbpm/kie-wb-common/pull/476/commits/c52590c3a4ba06dc35890623fb58a251706063f5 (in one of my pending 6.5.x PRs).

**Comment by Rikkola** [comment]
Thank you for the info. Every 6.5.x PR is hit by that.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
