### PR TITLE
(Temporary?) fix for failing tests...

### PR DESCRIPTION
**Pull request by manstis**
This PR is for review.. it fixes the failing tests on 6.3.x but IDK if the fix just masks the issue :(

@ederign @porcelli Any opinions?

### CODE REVIEW

**Comment by manstis** [comment]
I don't want to fiddle with the (possible) rogue commit: https://github.com/droolsjbpm/kie-uberfire-extensions/commit/17bcc2019582cc7e0a3454539abd51088e59c1c6 as it does "special" things for WAS...

**Comment by ederign** [comment]
@manstis I thought about that yesterday, but I'm a little bit afraid of masking the real issue because the error is not a Social error but a "File system is closed error" when this tests creates a social event that will be persisted.

**Comment by manstis** [comment]
Closed as this masks the issue.

**Comment by ederign** [comment]
@manstis  the question is: is that a FS issue or a error in test FS setup?

**Comment by ederign** [comment]
@manstis one think that I've noticed yesterday is that they use:

fs.forceAsDefault(); -> For a .SimpleFileSystemProvider but in the FS is closed is a JGit one.

(investigating).

**Pull request closed without merging**
