### PR TITLE
BZ1274349: Asset Management: Branch selector partially hidden

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1274349

Original PR for 6.3.x: https://github.com/droolsjbpm/kie-wb-common/pull/127

### CODE REVIEW

**Comment by csadilek** [comment]
@manstis this is the test I would add which works fine for me: https://gist.github.com/csadilek/1bd5438f6a004a30d347

If you agree I can simply amend it to this commit.

**Comment by manstis** [comment]
@csadilek Yeah, that's fine. I was trying to assert the widgets in the ```DropDownMenu```.

**Comment by csadilek** [comment]
@manstis I've updated the gist with a test that checks widgets are added when addBranch is called: https://gist.github.com/csadilek/1bd5438f6a004a30d347

Like you said bs3 text widget doesn't play nicely, but this works around it. In any case with these tests it should be good enough. wdyt?

**Comment by manstis** [comment]
Looks good... but it'd only work for adding a single branch. Also the clear
test could assert the menu has zero items. WDYT?

**Comment by manstis** [comment]
Let's merge and be done with :-)

**Comment by csadilek** [comment]
@manstis menu is a mock in this test, so to test that clear works on the menu we need to write a test for the GWT BS3 class DropDownMenu. Adding another test that add multiple branches. Then I will push.

**Comment by csadilek** [comment]
Thanks.

Pushed with tests amended:

master: 21c4cbc6b799818c143a2b8f61e09597d8391418

**Comment by manstis** [comment]
Thanks mate, looks good.

**Pull request closed without merging**
