### PR TITLE
JBPM-4833 - Data Modeller MVP, Tests, and related improvments

### PR DESCRIPTION
**Pull request by wmedvede**
- DataObjectBrowser responsive desing fixes

### CODE REVIEW

**Comment by wmedvede** [comment]
@manstis Hello Mike, would you mind review this PR.

Includes minor tunnings to make the datamodeler UI work better with the respnosive design. Should be included for the 6.4 community release.
Thanks!

@csadilek Includes the tunnings I've commented by email.

**Comment by manstis** [comment]
Walter, the test amended by this PR is commented out (+//@Test).... any reason - surely it should either be removed of fixed?

**Comment by wmedvede** [comment]
@manstis Mike, good catch. It was commented during debugging and I've forgot to uncomment it. It's already fixed. Thanks

**Comment by manstis** [comment]
+1 to merge.

**Comment by psiroky** [comment]
Merged into 6.4.x. @wmedvede please make sure to submit PR to master as well (if it is applicable there).

**Pull request merged**
