### PR TITLE
Roaster version update

### PR DESCRIPTION
**Pull request by wmedvede**

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @pefernan , would you mind review this PR.
Tanks.

note: this PR depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/369

**Comment by pefernan** [comment]
+1

**Comment by pefernan** [comment]
@wmedvede just a comment: try appformer before the PR gets merged, the source generation engine uses Roaster.

**Comment by wmedvede** [comment]
@pefernan  I confirm appformer is working with the new version.

**Pull request merged**
