### PR TITLE
Fix failing tests.

### PR DESCRIPTION
**Pull request by manstis**
@ederign @porcelli for review..

### CODE REVIEW

**Comment by manstis** [comment]
@etirelli @csadilek This will need merging in addition to https://github.com/uberfire/uberfire/pull/233

**Comment by ederign** [comment]
+1

**Comment by etirelli** [comment]
@manstis jenkins failed, I assume because of the UF PR was not merged yet?

@csadilek for coordination, I am working on this merge.

**Comment by mbiarnes** [comment]
UF is executing right now on Jenkins CI. So the needed changes of UF are not in yet.

**Comment by etirelli** [comment]
Merged.

**Pull request closed without merging**
