### PR TITLE
JavaSourceVisitor - add null check for method return type

### PR DESCRIPTION
**Pull request by mcimbora**
Constructors are included in the method list, however their return type is null. Avoid NPEs by adding null check.

### CODE REVIEW

**Comment by csadilek** [comment]
@mcimbora could you add a test for this, please? Seems this class isn't unit tested, but it's a good opportunity to start ;).

**Comment by mcimbora** [comment]
@csadilek Sure, will do.

**Comment by mcimbora** [comment]
@csadilek I updated the test coverage of `JavaSourceVisitor`.

**Comment by csadilek** [comment]
thanks @mcimbora, +1.

**Comment by manstis** [comment]
@mcimbora I noticed the same issue today (before seeing this PR). Could you please update the JIRA I raised https://issues.jboss.org/browse/GUVNOR-2653 accordingly?

**Pull request merged**
