### PR TITLE
BZ1269333: Result of searching Assets in Business Central's 'Full Text Search' includes duplicate records

### PR DESCRIPTION
**Pull request by manstis**
See https://github.com/droolsjbpm/kie-wb-common/pull/134

This is the cherry-pick to the 6.3.x branch.

### CODE REVIEW

**Comment by manstis** [comment]
@porcelli since you commented on the BZ care to review this?

**Comment by manstis** [comment]
The CI error is

```
[ERROR] /home/jenkins/workspace/kie-wb-common-pullrequests/kie-wb-common-services/kie-wb-common-refactoring/kie-wb-common-refactoring-backend/src/main/java/org/kie/workbench/common/services/refactoring/backend/server/util/KObjectUtil.java:[155,12] error: method does not override or implement a method from a supertype
```
The "offending" line is [this](https://github.com/droolsjbpm/kie-wb-common/pull/135/files#diff-45da1338bb8a2b5486ceca936b2eb550R156) however it does exist in the 0.7.x branch [here](https://github.com/uberfire/uberfire-extensions/pull/111/files#diff-078090c7b6208e805dd3cfd46858ad8eR30). 

I suspect the Jenkins job that builds "upstream" repositories does not work correctly when the branches have different names (or even supports branches?!?). ```6.3.x@kie-wb-common``` maps to ```0.7.x@uberfire-extensions```. I've compiled these changes locally and they're fine.

**Comment by manstis** [comment]
@psiroky Please see the Jenkins CI error and my comments above.. there might be an issue with configuration?

**Comment by psiroky** [comment]
The automation relies on matching branch names. This PR uses `BZ1269333_6.3.x` and the one for uf-ext uses `BZ1269333_0.7.x`. I don't think we can easily support this as everyone is using different branch names for different PR (e.g. someone uses prefix someone suffix).

**Comment by manstis** [comment]
@psiroky OK. np. In this case, the "fix" spans two repositories each on different branch names.. so the PR branch is correct per repository, but I understand this "inconsistency" is hard to cater for.

**Comment by porcelli** [comment]
https://github.com/droolsjbpm/kie-wb-common/commit/8d85b11a9b6d837812899d41c236e4edafbd7816

**Pull request closed without merging**
