### PR TITLE
JBPM-5405: Stunner - Add TaskName property to UserTask

### PR DESCRIPTION
**Pull request by jlindop**

### CODE REVIEW

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
@jlindop @tsurdilo @romartin this commit seems to be causing a compilation error (despite in being "green" here originally). I have to revert this commit. Can you please reopen/submit again.

**Comment by csadilek** [comment]
Problem is that BPMNDiagramMarshallerTest doesn't compile:  https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common/1394/org.kie.workbench.stunner$kie-wb-common-stunner-bpmn-backend/console

**Comment by jlindop** [comment]
@csadilek Yes, I'll redo this.

**Pull request merged**
