### PR TITLE
[6.3.x] Bug 1316566 - User can not create projects in any other repository than master

### PR DESCRIPTION
**Pull request by Rikkola**
Same as https://github.com/droolsjbpm/kie-wb-common/pull/318, but updated the commit message with a BZ number that depends on this fix.

See https://issues.jboss.org/browse/GUVNOR-2459

This is the corollary of #315 for 6.3.x

GUVNOR-2459: NPE when open an Organization Unit that doesn't have a repository yet

(cherry picked from commit a08a9e5a9c9299cb02bf0102138c31d0b944b31e)

Conflicts:
	kie-wb-common-screens/kie-wb-common-project-explorer/kie-wb-common-project-explorer-backend/src/test/java/org/kie/workbench/common/screens/explorer/backend/server/ProjectExplorerContentResolverTest.java

### CODE REVIEW

**Comment by Rikkola** [comment]
Now, not sure if I should +1 this or @manstis ;-)

+1

**Comment by manstis** [comment]
@Rikkola you can +1 since I made the code change :)

**Comment by manstis** [comment]
Waiting for @etirelli to give the go ahead before merging...

**Comment by Rikkola** [comment]
Thank you. All in now.

**Pull request merged**
