### PR TITLE
JBPM-5389: Stunner - SVG support & New BPMN shapes.

### PR DESCRIPTION
**Pull request by romartin**
This commit basically:
* Added SVG support modules & types.
* Refactor of the BPMN shapes for using the SVG views produced from the icons provided by UXD.

Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/394
See details [here](https://issues.jboss.org/browse/JBPM-5389).

### CODE REVIEW

**Comment by romartin** [comment]
Hey @manstis @hasys 

Here it is the svg stuff and new shapes for the BPMN module. Will notice the initial rendering on the authoring screen it's a bit slower, just doing cleans and trying to improve this, but rather than this I think the other stuff is ready, also because @manstis depends on this commit as well.
Thanks!

**Comment by romartin** [comment]
@manstis the failed test seems not related with this commit... let's try again

Jenkins please retest this

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by romartin** [comment]
oh @hasys @manstis , you're right, the showcase-project does not starts.. but neither in master branch for me! The exception is really self-explanatory `$wnd.JQuery is not a function`... not first time I see this, but do not rememer why it's due to... any ideas? Will keep researching..

**Comment by romartin** [comment]
Jenkins please retest this.

**Comment by romartin** [comment]
Hey @manstis , @hasys 

I've been the whole day working on this again, updates:

1.- About tests - Added more tests for almost all  generators stuff and the svg factories, The test coverage and the already missing tests for changed classes can be improved/added in further iterations, in fact both QE and eng have time slots estimated for this! So I think this can be enough for merging and letting @manstis move forward.

2.- About the showcase project - Still not sure why it does not works, but same happens right now on master. The standalone stunner's showcase and the kie-wb are working fine. Trying to figure out if the issue is on the default demo repository it is using (jbpm-console-ng-playground-kar) or related.. @manstis any ideas? getting crazy adding more wb and drools-wb dependencies but I would like not to end up in a complete wb showcase on stunner.. will keep trying

3.- About the Jenkins build failed - The error is really really strange... @psiroky  sorry for bothering, any clues would be appreciated...:)

@manstis summary - the maven build, standalone showcase and kie-wb are working, not working  the project showcase, but same happening on master.. so up to you if you need this and you want to merge it, it's ready

Thanks!

**Comment by psiroky** [comment]
The build error was caused by me forgetting to merge one of 7 related PRs.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@hasys @romartin See https://github.com/uberfire/uberfire/pull/634 this fixes the "Loading..." issue.

**Comment by manstis** [comment]
@hasys Hi... are you OK if we merge this now? I really need these changes to further my Case Modeller work. Could any concerns about test coverage be added as sub-tasks to https://issues.jboss.org/browse/JBPM-5389?

**Comment by manstis** [comment]
@romartin I am merging this PR; please could you log somewhere that we need to improve test coverage.

**Pull request merged**
