### PR TITLE
GUVNOR-2670: Screens on 'Authoring->Project Authoring' of business-central are opened by default

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/GUVNOR-2670

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by manstis** [comment]
@karreiro A test would be nice (just confirming ```PerspectiveManager.savePerspectiveState()``` is called when ```LogoutCommand.execute()``` is called)...

**Comment by karreiro** [comment]
Thanks @manstis

**Comment by manstis** [comment]
+1 to merge. Thanks @karreiro

**Pull request merged**
