### PR TITLE
DROOLS-733 - UI fixes for KieServer, added possibility to update serv…

### PR DESCRIPTION
**Pull request by mswiderski**
…er instances status from UI

### CODE REVIEW

**Comment by manstis** [comment]
@mswiderski Unfortunately tests ```BoxPresenterTest.testSetupLoadingServerRef()``` and ```BoxPresenterText.testSetupLoadingServer()``` fail with this PR.

**Comment by mswiderski** [comment]
thanks @manstis it was more for local try outs and more improvements are on the way. Will update this PR when they are ready and make sure all tests pass.

**Comment by manstis** [comment]
Thanks.. and if we're really following the law of the land.. I shouldn't
really accept this PR until the documentation has been updated too.. but
assuming this is to be done when the Kie Server refactor is complete I can
let this slip... for now... :)

**Comment by mswiderski** [comment]
@manstis tests fixed so this PR is good to go from my point of view

docs will be updated once we have stable/satisfying kie server hopefully within a week or so (thanks a lot for trying it out and finding issues:))

**Comment by manstis** [comment]
(master) http://github.com/droolsjbpm/kie-wb-common/commit/eefae8912

(6.3.x) http://github.com/droolsjbpm/kie-wb-common/commit/6713f6d7b

**Pull request closed without merging**
