### PR TITLE
add backslashes to semicolons preventing Zanata to add backslashes ra…

### PR DESCRIPTION
**Pull request by mbiarnes**
…ising a new PRs

Added backslashes to  .../workbench/common/screens/server/management/client/resources/i18n/Constants_ja.properties  to prevent Zanata, when doing next zanata:pull-module to add them automatically and raise a PR.
This was tested. kie-wb-commons builds. Doing another mvn zanata:pull-module followed by mvn replacer:replace -N there were no changes.
The kie-eap_6.4war was deployed to EAP 6.4 and  there were not anymore the screens visible in 
https://issues.jboss.org/browse/RHBPMS-1367?jql=assignee%3Dpaulovmr

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mbiarnes both zh_CN and zh_TW also have unescaped semi colon, I'm wondering if those should be changed as well. Isn't Zanata creating changes for those files?

**Comment by mbiarnes** [comment]
@cristianonicolai this is what I don't understand at all.
Doing mvn zanata:pull--module and mvn replacer:replace -N in kie-wb-common, there is only left 
[Constants_ja.properties](https://github.com/droolsjbpm/kie-wb-common/blob/6.5.x/kie-wb-common-screens/kie-wb-common-server-ui/kie-wb-common-server-ui-client/src/main/resources/org/kie/workbench/common/screens/server/management/client/resources/i18n/Constants_ja.properties) where the backslashes are added as i.e. the French translation or Spanish translation have already the backslash. No zh_CN and zh_TW doesn't, but a backslash isn't added when doing the zanata:pull-module.
To prevent with each pull-module to pull the Japanese translation and adding the backslashes (so nothing changed at all) I added it in the Constants_ja.properties to get rid of this "fake-change".
I don't know why for zn_CG and zh_TW the backslashes aren't added? After a mvn zanata:pull-module there are no backslashes added - so Zanata creates backslashes for all languages except for zh_CN and zh_TW?

**Comment by cristianonicolai** [comment]
@mbiarnes well that's interesting... would have to chase the guys in the Zanata team to try to figure it out. Not sure why but I would expect to be consistent across languages.

**Comment by cristianonicolai** [comment]
+1

**Pull request merged**
