### PR TITLE
BZ1301816: GDT: Editor is not displayed if operation 'is contained in the (comma separated) list' is selected

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1301816

### CODE REVIEW

**Comment by csadilek** [comment]
@manstis I'd say let's add a test for it since it's seems simple enough to do but I can be convinced otherwise if you classify this as a pure layout change?

Could be as simple as this....

```java
@RunWith(GwtMockitoTestRunner.class)
public class PopupDrownDownEditCellTest {
    
    @Test
    public void getLabel() {
        final ListBox box = Mockito.mock( ListBox.class );
        final PopupDropDownEditCell cell = new  PopupDropDownEditCell(box);
        when(box.getItemCount()).thenReturn( 2 );
        when(box.getValue( 0 )).thenReturn( "value0" );
        when(box.getValue( 1 )).thenReturn( "value1" );
        when(box.getItemText( 1 )).thenReturn( "value1" );
        
        assertEquals("value1", cell.getLabel( "value1" ));
    }
 
}
```

**Comment by manstis** [comment]
No, you've convinced me to write a test - I'll update PRs tomorrow (that'll
teach me for being lazy)

**Comment by manstis** [comment]
@csadilek Tests added.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: de93e3ff0fad96a48abb1ffc81be4df97e619bc0

**Pull request closed without merging**
